### ISSUE TITLE
Tutorial on https://vector.dev/docs/setup/installation/operating-systems/raspbian/ failed

### ISSUE THREAD

**Issue by jakeswenson** [timberio/vector#2301]
The tutorial on:

https://vector.dev/docs/setup/installation/operating-systems/raspbian/

Here's what went wrong:

```bash
pi@rpi5:~ $ uname -a
Linux rpi5 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
pi@rpi5:~ $ curl --proto '=https' --tlsv1.2 -sSf https://sh.vector.dev | sh
                                   __   __  __
                                   \ \ / / / /
                                    \ V / / /
                                     \_/  \/

                                   V E C T O R
                                    Installer


--------------------------------------------------------------------------------
Website: https://vector.dev
Docs: https://vector.dev/docs/
Community: https://vector.dev/community/
--------------------------------------------------------------------------------

>>> We'll be installing Vector via the dpkg package at https://packages.timber.io/vector/latest/
>>> Ready to proceed? (y/n)

>>> y

--------------------------------------------------------------------------------

>>> unsupported arch: armv7-unknown-linux-gnueabihf
```

Claims my arch is not supported but I'm running raspbian and following the raspbian tutorial...

**Comment by binarylogic** [comment]
Thanks for reporting @jakeswenson. We'll get this sorted out.

**Comment by jakeswenson** [comment]
I should note i was able to download the dpkg and install it using the manual instructions, so thank you for those!

**Comment by a-rodin** [comment]
It was recently fixed here:
https://github.com/timberio/vector/blob/fb8ae10f193c1990259500941ddd90f01472063e/distribution/install.sh#L127-L132

but https://sh.vector.dev/ has not been updated yet because it is updated only on new releases. In the meantime, it is possible to run

```curl
curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/timberio/vector/master/distribution/install.sh | sh
```
instead of
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.vector.dev | sh
```

**Comment by jakeswenson** [comment]
I just reset my raspbian pi machine, and tried this again (both from docs and from your script above) and I'm getting the same error....

## Using your script 
```bash
pi@rpi5:~ $ curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/timberio/vector/master/distribution/install.sh | sh

                                   __   __  __
                                   \ \ / / / /
                                    \ V / / /
                                     \_/  \/

                                   V E C T O R
                                    Installer


--------------------------------------------------------------------------------
Website: https://vector.dev
Docs: https://vector.dev/docs/
Community: https://vector.dev/community/
--------------------------------------------------------------------------------

>>> We'll be installing Vector via a pre-built archive at https://packages.timber.io/vector/latest/
>>> Ready to proceed? (y/n)

>>> Please enter y or n.
>>> y

--------------------------------------------------------------------------------

>>> unsupported arch: armv7-unknown-linux-gnueabihf
pi@rpi5:~ $ uname -a
Linux rpi5 5.4.72-v7l+ #1356 SMP Thu Oct 22 13:57:51 BST 2020 armv7l GNU/Linux
```

## Docs
using the [docs here](https://vector.dev/docs/setup/installation/operating-systems/raspbian/)

```bash
pi@rpi5:~ $ uname -a
Linux rpi5 5.4.72-v7l+ #1356 SMP Thu Oct 22 13:57:51 BST 2020 armv7l GNU/Linux
pi@rpi5:~ $ curl --proto '=https' --tlsv1.2 -sSf https://sh.vector.dev | sh
                                   __   __  __
                                   \ \ / / / /
                                    \ V / / /
                                     \_/  \/

                                   V E C T O R
                                    Installer


--------------------------------------------------------------------------------
Website: https://vector.dev
Docs: https://vector.dev/docs/
Community: https://vector.dev/community/
--------------------------------------------------------------------------------

>>> We'll be installing Vector via the dpkg package at https://packages.timber.io/vector/latest/
>>> Ready to proceed? (y/n)

>>> y

--------------------------------------------------------------------------------

>>> unsupported arch: armv7-unknown-linux-gnueabihf
```

This, for me, appears to still not be resolved.

@binarylogic @a-rodin Can you confirm this is indeed fixed?

**Comment by jakeswenson** [comment]
OK nevermind, looks like with #3352 there is no desire to support `armv7`... The docs site needs to be updated....

**Comment by jakeswenson** [comment]
FWIW vector ran flawlessly on my raspberry pi. i guess its back to `fluentd`/`fluentbit` 😞

**Comment by jamtur01** [comment]
Hi @jakeswenson I am sorry about the arm7 support but in our previous build environment it was very mess to build. We've recently moved over to `cross` for our builds and we're planning to add it back. I'll make a note to try it later this week.

**Comment by jamtur01** [comment]
And because I had some time over lunch: #4871. :)
