### ISSUE TITLE
Add a way to select _only_ certain fields in VRL

### ISSUE THREAD

**Issue by jszwedko** [timberio/vector#7347]
Requested by user in discord: https://discord.com/channels/742820443487993987/764187584452493323/839503742813732884

We had an `only_fields` at one point, but it got backed out. I can't remember why though.

**Comment by JeanMertz** [comment]
> We had an `only_fields` at one point, but it got backed out. I can't remember why though.

The reason was that it was sufficiently different from other functions (in that it was the only one that had a (hacky) way to provide a variable number of arguments to it, up to a limit of 32) that we wanted to take our time getting that right.

It was also discussed that having iteration in the future would make this function obsolete, as you could do this via iteration + `del` (but this wasn't the reason we backed out of the function).

**Comment by jszwedko** [comment]
Aha I see.

We could support it with our current compiler with something like:

```
. = only_fields(., ["field1", "field2", "field3"])
```

I realize this differs a bit from `del()` though in that it takes paths as strings.

This would also be solved by iteration.

**Comment by JeanMertz** [comment]
> I realize this differs a bit from `del()` though in that it takes paths as strings.

Yeah, I'm not a fan of mixing "fields" (string type) and "paths" (path type) for the approximately same use-case. I'd prefer it if we stick to paths wherever they are needed, but I also reckon there's still some gaps there for that to be a viable solution everywhere.

> This would also be solved by iteration.

Indeed. Although there we'd still have the issue that paths are currently evaluated at the call site, so you couldn't do something like `foo = [.foo, .bar]`, as that would expand to `foo = [<value of .foo>, <value of .bar>]`. Nothing we can't solve, but worth pointing out as a blocker for allowing iteration over paths.
